id: 6eaa4f0efe284752b50151f442b8f073
initial_creation_type: ocr
source_metadata:
  volumes:
    311b310ee5fd4b938a0d7d0e1db9a3cc:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
